### PR TITLE
Transcription errors

### PR DESCRIPTION
**Pull request by tipabu**
Three transcription errors, or products thereof. Individual commits have more details. Corrections also submitted to PG.

### CODE REVIEW

**Comment by acabal** [comment]
I think we should keep `ain't`, can you rebase that commit out of this PR?

**Comment by tipabu** [comment]
Can do! Want me to include a modernize-spelling commit for the other instances of `aint` in chapter XIII?

**Comment by acabal** [comment]
Sure!

**Comment by tipabu** [comment]
Kept the `ain't` -> `aint` transcription fix commit, but rolled it back as part of the editorial. That seemed to best match the intent of having the editorial commits flagged as such.

**Comment by acabal** [comment]
Thanks!

**Pull request merged**
